name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Jalankan setiap hari pada tengah malam UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: crashnburn01 # Ganti dengan nama pengguna GitHub Anda
          gif_out_path: ./output/github-contribution-grid-snake.gif # Lokasi output GIF
          svg_out_path: ./output/github-contribution-grid-snake.svg # Lokasi output SVG

      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
